// Common parliamentary motions raised on the floor of an MUN committee,
// phrased the way a chair would read them aloud.
export const MOTIONS = [
  "Open a Moderated Caucus",
  "Open an Unmoderated Caucus",
  "Open the General Speaker's List",
  "Close the General Speaker's List",
  "Extend the Speaking Time",
  "Extend the Moderated Caucus",
  "Introduce a Draft Resolution",
  "Introduce an Amendment",
  "Move into Voting Procedure",
  "Suspend the Meeting",
  "Adjourn the Meeting",
];

// Ported from excelToJson/assets/constants.js — kept in sync by hand, not by
// a build step. If you change the word lists there, mirror the change here.

export const countries = [
  { name: "Afghanistan", code: "AFG" },
  { name: "Albania", code: "ALB" },
  { name: "Algeria", code: "ALG" },
  { name: "Andorra", code: "AND" },
  { name: "Angola", code: "ANG" },
  { name: "Antigua and Barbuda", code: "ATG" },
  { name: "Argentina", code: "ARG" },
  { name: "Armenia", code: "ARM" },
  { name: "Australia", code: "AUS" },
  { name: "Austria", code: "AUT" },
  { name: "Azerbaijan", code: "AZE" },
  { name: "Bahamas", code: "BAH" },
  { name: "Bahrain", code: "BHR" },
  { name: "Bangladesh", code: "BAN" },
  { name: "Barbados", code: "BAR" },
  { name: "Belarus", code: "BLR" },
  { name: "Belgium", code: "BEL" },
  { name: "Belize", code: "BLZ" },
  { name: "Benin", code: "BEN" },
  { name: "Bhutan", code: "BHU" },
  { name: "Bolivia", code: "BOL" },
  { name: "Bosnia and Herzegovina", code: "BIH" },
  { name: "Botswana", code: "BOT" },
  { name: "Brazil", code: "BRA" },
  { name: "Brunei", code: "BRU" },
  { name: "Bulgaria", code: "BUL" },
  { name: "Burkina Faso", code: "BUR" },
  { name: "Burundi", code: "BDI" },
  { name: "Cabo Verde", code: "CPV" },
  { name: "Cambodia", code: "CAM" },
  { name: "Cameroon", code: "CMR" },
  { name: "Canada", code: "CAN" },
  { name: "Central African Republic", code: "CAR" },
  { name: "Chad", code: "CHA" },
  { name: "Chile", code: "CHI" },
  { name: "China", code: "CHN" },
  { name: "Colombia", code: "COL" },
  { name: "Comoros", code: "COM" },
  { name: "Congo", code: "CGO" },
  { name: "Costa Rica", code: "CRC" },
  { name: "Côte d'Ivoire", code: "CIV" },
  { name: "Croatia", code: "CRO" },
  { name: "Cuba", code: "CUB" },
  { name: "Cyprus", code: "CYP" },
  { name: "Czechia", code: "CZE" },
  { name: "North Korea", code: "DPRK" },
  { name: "DR Congo", code: "DRC" },
  { name: "Denmark", code: "DEN" },
  { name: "Djibouti", code: "DJI" },
  { name: "Dominica", code: "DMA" },
  { name: "Dominican Republic", code: "DOM" },
  { name: "Ecuador", code: "ECU" },
  { name: "Egypt", code: "EGY" },
  { name: "El Salvador", code: "ESA" },
  { name: "Equatorial Guinea", code: "GEQ" },
  { name: "Eritrea", code: "ERI" },
  { name: "Estonia", code: "EST" },
  { name: "Eswatini", code: "SWZ" },
  { name: "Ethiopia", code: "ETH" },
  { name: "Fiji", code: "FIJ" },
  { name: "Finland", code: "FIN" },
  { name: "France", code: "FRA" },
  { name: "Gabon", code: "GAB" },
  { name: "Gambia", code: "GAM" },
  { name: "Georgia", code: "GEO" },
  { name: "Germany", code: "GER" },
  { name: "Ghana", code: "GHA" },
  { name: "Greece", code: "GRE" },
  { name: "Grenada", code: "GRN" },
  { name: "Guatemala", code: "GUA" },
  { name: "Guinea", code: "GUI" },
  { name: "Guinea-Bissau", code: "GBS" },
  { name: "Guyana", code: "GUY" },
  { name: "Haiti", code: "HAI" },
  { name: "Honduras", code: "HON" },
  { name: "Hungary", code: "HUN" },
  { name: "Iceland", code: "ISL" },
  { name: "India", code: "IND" },
  { name: "Indonesia", code: "INA" },
  { name: "Iran", code: "IRI" },
  { name: "Iraq", code: "IRQ" },
  { name: "Ireland", code: "IRL" },
  { name: "Israel", code: "ISR" },
  { name: "Italy", code: "ITA" },
  { name: "Jamaica", code: "JAM" },
  { name: "Japan", code: "JPN" },
  { name: "Jordan", code: "JOR" },
  { name: "Kazakhstan", code: "KAZ" },
  { name: "Kenya", code: "KEN" },
  { name: "Kiribati", code: "KIR" },
  { name: "Kuwait", code: "KUW" },
  { name: "Kyrgyzstan", code: "KGZ" },
  { name: "Laos", code: "LAO" },
  { name: "Latvia", code: "LAT" },
  { name: "Lebanon", code: "LBN" },
  { name: "Lesotho", code: "LES" },
  { name: "Liberia", code: "LBR" },
  { name: "Libya", code: "LBA" },
  { name: "Liechtenstein", code: "LIE" },
  { name: "Lithuania", code: "LTU" },
  { name: "Luxembourg", code: "LUX" },
  { name: "Madagascar", code: "MAD" },
  { name: "Malawi", code: "MAW" },
  { name: "Malaysia", code: "MAS" },
  { name: "Maldives", code: "MDV" },
  { name: "Mali", code: "MLI" },
  { name: "Malta", code: "MLT" },
  { name: "Marshall Islands", code: "MHL" },
  { name: "Mauritania", code: "MTN" },
  { name: "Mauritius", code: "MRI" },
  { name: "Mexico", code: "MEX" },
  { name: "Micronesia", code: "FSM" },
  { name: "Monaco", code: "MON" },
  { name: "Mongolia", code: "MGL" },
  { name: "Montenegro", code: "MNE" },
  { name: "Morocco", code: "MAR" },
  { name: "Mozambique", code: "MOZ" },
  { name: "Myanmar", code: "MYA" },
  { name: "Namibia", code: "NAM" },
  { name: "Nauru", code: "NRU" },
  { name: "Nepal", code: "NEP" },
  { name: "Netherlands", code: "NED" },
  { name: "New Zealand", code: "NZL" },
  { name: "Nicaragua", code: "NCA" },
  { name: "Niger", code: "NIG" },
  { name: "Nigeria", code: "NGR" },
  { name: "North Macedonia", code: "MKD" },
  { name: "Norway", code: "NOR" },
  { name: "Oman", code: "OMA" },
  { name: "Pakistan", code: "PAK" },
  { name: "Palau", code: "PLW" },
  { name: "Panama", code: "PAN" },
  { name: "Papua New Guinea", code: "PNG" },
  { name: "Paraguay", code: "PAR" },
  { name: "Peru", code: "PER" },
  { name: "Philippines", code: "PHI" },
  { name: "Poland", code: "POL" },
  { name: "Portugal", code: "POR" },
  { name: "Qatar", code: "QAT" },
  { name: "South Korea", code: "ROK" },
  { name: "Moldova", code: "MDA" },
  { name: "Romania", code: "ROU" },
  { name: "Russia", code: "RUS" },
  { name: "Rwanda", code: "RWA" },
  { name: "Saint Kitts and Nevis", code: "SKN" },
  { name: "Saint Lucia", code: "LCA" },
  { name: "Saint Vincent and the Grenadines", code: "VIN" },
  { name: "Samoa", code: "SAM" },
  { name: "San Marino", code: "SMR" },
  { name: "Sao Tome and Principe", code: "STP" },
  { name: "Saudi Arabia", code: "KSA" },
  { name: "Senegal", code: "SEN" },
  { name: "Serbia", code: "SRB" },
  { name: "Seychelles", code: "SEY" },
  { name: "Sierra Leone", code: "SLE" },
  { name: "Singapore", code: "SGP" },
  { name: "Slovakia", code: "SVK" },
  { name: "Slovenia", code: "SLO" },
  { name: "Solomon Islands", code: "SOL" },
  { name: "Somalia", code: "SOM" },
  { name: "South Africa", code: "RSA" },
  { name: "South Sudan", code: "SSD" },
  { name: "Spain", code: "ESP" },
  { name: "Sri Lanka", code: "SRI" },
  { name: "Sudan", code: "SUD" },
  { name: "Suriname", code: "SUR" },
  { name: "Sweden", code: "SWE" },
  { name: "Switzerland", code: "SUI" },
  { name: "Syria", code: "SYR" },
  { name: "Tajikistan", code: "TJK" },
  { name: "Thailand", code: "THA" },
  { name: "Timor-Leste", code: "TLS" },
  { name: "Togo", code: "TOG" },
  { name: "Tonga", code: "TGA" },
  { name: "Trinidad and Tobago", code: "TTO" },
  { name: "Tunisia", code: "TUN" },
  { name: "Turkey", code: "TUR" },
  { name: "Turkmenistan", code: "TKM" },
  { name: "Tuvalu", code: "TUV" },
  { name: "Uganda", code: "UGA" },
  { name: "Ukraine", code: "UKR" },
  { name: "United Arab Emirates", code: "UAE" },
  { name: "United Kingdom", code: "UK" },
  { name: "Tanzania", code: "TAN" },
  { name: "United States", code: "USA" },
  { name: "Uruguay", code: "URU" },
  { name: "Uzbekistan", code: "UZB" },
  { name: "Vanuatu", code: "VAN" },
  { name: "Venezuela", code: "VEN" },
  { name: "Vietnam", code: "VIE" },
  { name: "Yemen", code: "YEM" },
  { name: "Zambia", code: "ZAM" },
  { name: "Zimbabwe", code: "ZIM" },
];

// Deliberately excludes generic words like "director"/"secretary"/"representative"/
// "officer": in real allocation sheets those also show up as delegate portfolio
// names (e.g. a crisis committee delegate called "BSAA Director" or "UNSC
// Representative"), so treating them as chair/page signals would misclassify data.
export const CHAIR_WORDS = new RegExp([
  "CHAIR",
  "PRESIDENT",
  "EDITOR",
  "DAIS",
  "MODERATOR",
  "PRESIDING",
  "RAPPORTEUR",
].join("|"));

export const PAGE_WORDS = new Set([
  "PAGE",
  "PAGES",
  "COURSIER",
  "COURSIERS",
  "MESSENGER",
  "MESSENGERS",
  "RUNNER",
  "RUNNERS",
  "USHER",
  "USHERS",
]);

// Sheet names (exact, case-insensitive) that are never a real committee -
// cover/instructions/summary tabs some conferences include alongside the
// actual committee sheets.
export const SKIP_SHEETS = new Set([
  "teams",
  "information",
  "info",
  "cover",
  "cover page",
  "instructions",
  "read me",
  "readme",
  "summary",
  "notes",
  "overview",
]);

// Exact-match signals (post normalize()) that a row is a header row, and
// which field a header column maps to. Kept as sets (not a regex/substring
// check) because these are compared against a whole header cell, not
// scanned for as a substring of arbitrary data - "Delegate"/"Student" as a
// whole cell is a safe signal; as a substring of someone's real name it
// would not be.
export const NAME_WORDS = new Set([
  "NAME",
  "NOM",
  "NOMBRE",
  "DELEGATE",
  "STUDENT",
  "PARTICIPANT",
  "FULL NAME",
]);

export const EMAIL_WORDS = new Set([
  "EMAIL",
  "E-MAIL",
  "MAIL",
  "CORREO",
]);

export const TOPIC_WORDS = new Set([
  "TOPIC",
  "SUJET",
  "QUESTION",
  "THEME",
]);
