// Common parliamentary motions raised on the floor of an MUN committee,
// phrased the way a chair would read them aloud.
export const MOTIONS = [
  "Open a Moderated Caucus",
  "Open an Unmoderated Caucus",
  "Open the General Speaker's List",
  "Close the General Speaker's List",
  "Extend the Speaking Time",
  "Extend the Moderated Caucus",
  "Introduce a Draft Resolution",
  "Introduce an Amendment",
  "Move into Voting Procedure",
  "Suspend the Meeting",
  "Adjourn the Meeting",
];

// Ported from excelToJson/assets/constants.js — kept in sync by hand, not by
// a build step. If you change the word lists there, mirror the change here.
// Official ISO 3166-1 alpha-3 codes (cross-checked against the ISO OBP and
// Wikipedia's mirror of it). `name` is the display name; `alias` (when
// present) lists other names MUN allocation sheets use for the same country
// (e.g. official long form, informal/former names) - AllocationParser
// matches a cell's country name against both.
export const countries = [
  { name: "Afghanistan", code: "AFG" },
  { name: "Albania", code: "ALB" },
  { name: "Algeria", code: "DZA" },
  { name: "American Samoa", code: "ASM" },
  { name: "Andorra", code: "AND" },
  { name: "Angola", code: "AGO" },
  { name: "Anguilla", code: "AIA" },
  { name: "Antarctica", code: "ATA" },
  { name: "Antigua and Barbuda", code: "ATG" },
  { name: "Argentina", code: "ARG" },
  { name: "Armenia", code: "ARM" },
  { name: "Aruba", code: "ABW" },
  { name: "Australia", code: "AUS" },
  { name: "Austria", code: "AUT" },
  { name: "Azerbaijan", code: "AZE" },
  { name: "Bahamas", code: "BHS", alias: ["The Bahamas"] },
  { name: "Bahrain", code: "BHR" },
  { name: "Bangladesh", code: "BGD" },
  { name: "Barbados", code: "BRB" },
  { name: "Belarus", code: "BLR", alias: ["Byelorussian SSR", "Byelorussia"] },
  { name: "Belgium", code: "BEL" },
  { name: "Belize", code: "BLZ" },
  { name: "Benin", code: "BEN", alias: ["Dahomey"] },
  { name: "Bermuda", code: "BMU" },
  { name: "Bhutan", code: "BTN" },
  { name: "Bolivia", code: "BOL", alias: ["Plurinational State of Bolivia"] },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BES" },
  { name: "Bosnia and Herzegovina", code: "BIH", alias: ["Bosnia"] },
  { name: "Botswana", code: "BWA" },
  { name: "Bouvet Island", code: "BVT" },
  { name: "Brazil", code: "BRA" },
  { name: "British Indian Ocean Territory", code: "IOT" },
  { name: "Brunei", code: "BRN", alias: ["Brunei Darussalam"] },
  { name: "Bulgaria", code: "BGR" },
  { name: "Burkina Faso", code: "BFA", alias: ["Upper Volta"] },
  { name: "Burundi", code: "BDI" },
  { name: "Cabo Verde", code: "CPV", alias: ["Cape Verde"] },
  { name: "Cambodia", code: "KHM" },
  { name: "Cameroon", code: "CMR" },
  { name: "Canada", code: "CAN" },
  { name: "Cayman Islands", code: "CYM" },
  { name: "Central African Republic", code: "CAF", alias: ["CAR"] },
  { name: "Chad", code: "TCD" },
  { name: "Chile", code: "CHL" },
  { name: "China", code: "CHN", alias: ["People's Republic of China", "PRC"] },
  { name: "Christmas Island", code: "CXR" },
  { name: "Cocos (Keeling) Islands", code: "CCK" },
  { name: "Colombia", code: "COL" },
  { name: "Comoros", code: "COM" },
  { name: "Congo", code: "COG", alias: ["Republic of Congo", "Congo-Brazzaville"] },
  { name: "Cook Islands", code: "COK" },
  { name: "Costa Rica", code: "CRI" },
  { name: "Croatia", code: "HRV" },
  { name: "Cuba", code: "CUB" },
  { name: "Curaçao", code: "CUW", alias: ["Curacao"] },
  { name: "Cyprus", code: "CYP" },
  { name: "Czechia", code: "CZE", alias: ["Czech Republic"] },
  { name: "Côte d'Ivoire", code: "CIV", alias: ["Ivory Coast", "Cote d'Ivoire"] },
  { name: "Denmark", code: "DNK" },
  { name: "Djibouti", code: "DJI", alias: ["French Afars and Issas"] },
  { name: "Dominica", code: "DMA" },
  { name: "Dominican Republic", code: "DOM" },
  { name: "DR Congo", code: "COD", alias: ["Congo, Democratic Republic", "DRC", "Congo-Kinshasa", "Zaire"] },
  { name: "Ecuador", code: "ECU" },
  { name: "Egypt", code: "EGY" },
  { name: "El Salvador", code: "SLV" },
  { name: "Equatorial Guinea", code: "GNQ" },
  { name: "Eritrea", code: "ERI" },
  { name: "Estonia", code: "EST" },
  { name: "Eswatini", code: "SWZ", alias: ["Swaziland"] },
  { name: "Ethiopia", code: "ETH" },
  { name: "Falkland Islands (Malvinas)", code: "FLK", alias: ["Malvinas"] },
  { name: "Faroe Islands", code: "FRO" },
  { name: "Fiji", code: "FJI" },
  { name: "Finland", code: "FIN" },
  { name: "France", code: "FRA" },
  { name: "French Guiana", code: "GUF" },
  { name: "French Polynesia", code: "PYF" },
  { name: "French Southern Territories", code: "ATF" },
  { name: "Gabon", code: "GAB" },
  { name: "Gambia", code: "GMB", alias: ["The Gambia"] },
  { name: "Georgia", code: "GEO" },
  { name: "Germany", code: "DEU" },
  { name: "Ghana", code: "GHA" },
  { name: "Gibraltar", code: "GIB" },
  { name: "Greece", code: "GRC" },
  { name: "Greenland", code: "GRL" },
  { name: "Grenada", code: "GRD" },
  { name: "Guadeloupe", code: "GLP" },
  { name: "Guam", code: "GUM" },
  { name: "Guatemala", code: "GTM" },
  { name: "Guernsey", code: "GGY" },
  { name: "Guinea", code: "GIN" },
  { name: "Guinea-Bissau", code: "GNB" },
  { name: "Guyana", code: "GUY" },
  { name: "Haiti", code: "HTI" },
  { name: "Heard Island and McDonald Islands", code: "HMD" },
  { name: "Holy See", code: "VAT", alias: ["Vatican City"] },
  { name: "Honduras", code: "HND" },
  { name: "Hong Kong", code: "HKG", alias: ["Hong Kong SAR"] },
  { name: "Hungary", code: "HUN" },
  { name: "Iceland", code: "ISL" },
  { name: "India", code: "IND", alias: ["Bharat"] },
  { name: "Indonesia", code: "IDN" },
  { name: "Iran", code: "IRN", alias: ["Iran, Islamic Republic"] },
  { name: "Iraq", code: "IRQ" },
  { name: "Ireland", code: "IRL", alias: ["Republic of Ireland"] },
  { name: "Isle of Man", code: "IMN" },
  { name: "Israel", code: "ISR" },
  { name: "Italy", code: "ITA" },
  { name: "Jamaica", code: "JAM" },
  { name: "Japan", code: "JPN" },
  { name: "Jersey", code: "JEY" },
  { name: "Jordan", code: "JOR" },
  { name: "Kazakhstan", code: "KAZ" },
  { name: "Kenya", code: "KEN" },
  { name: "Kiribati", code: "KIR" },
  { name: "Kuwait", code: "KWT" },
  { name: "Kyrgyzstan", code: "KGZ" },
  { name: "Laos", code: "LAO", alias: ["Lao People's Democratic Republic", "Lao PDR"] },
  { name: "Latvia", code: "LVA" },
  { name: "Lebanon", code: "LBN" },
  { name: "Lesotho", code: "LSO" },
  { name: "Liberia", code: "LBR" },
  { name: "Libya", code: "LBY" },
  { name: "Liechtenstein", code: "LIE" },
  { name: "Lithuania", code: "LTU" },
  { name: "Luxembourg", code: "LUX" },
  { name: "Macao", code: "MAC", alias: ["Macau"] },
  { name: "Madagascar", code: "MDG" },
  { name: "Malawi", code: "MWI" },
  { name: "Malaysia", code: "MYS" },
  { name: "Maldives", code: "MDV" },
  { name: "Mali", code: "MLI" },
  { name: "Malta", code: "MLT" },
  { name: "Marshall Islands", code: "MHL", alias: ["RMI"] },
  { name: "Martinique", code: "MTQ" },
  { name: "Mauritania", code: "MRT" },
  { name: "Mauritius", code: "MUS" },
  { name: "Mayotte", code: "MYT" },
  { name: "Mexico", code: "MEX" },
  { name: "Micronesia", code: "FSM", alias: ["Micronesia, Federated States", "FSM"] },
  { name: "Moldova", code: "MDA", alias: ["Moldova, Republic"] },
  { name: "Monaco", code: "MCO" },
  { name: "Mongolia", code: "MNG" },
  { name: "Montenegro", code: "MNE" },
  { name: "Montserrat", code: "MSR" },
  { name: "Morocco", code: "MAR" },
  { name: "Mozambique", code: "MOZ" },
  { name: "Myanmar", code: "MMR", alias: ["Burma"] },
  { name: "Namibia", code: "NAM" },
  { name: "Nauru", code: "NRU" },
  { name: "Nepal", code: "NPL" },
  { name: "Netherlands", code: "NLD", alias: ["Netherlands, Kingdom", "Holland"] },
  { name: "New Caledonia", code: "NCL" },
  { name: "New Zealand", code: "NZL", alias: ["Aotearoa"] },
  { name: "Nicaragua", code: "NIC" },
  { name: "Niger", code: "NER" },
  { name: "Nigeria", code: "NGA" },
  { name: "Niue", code: "NIU" },
  { name: "Norfolk Island", code: "NFK" },
  { name: "North Macedonia", code: "MKD", alias: ["Macedonia", "FYROM"] },
  { name: "Northern Mariana Islands", code: "MNP" },
  { name: "Norway", code: "NOR" },
  { name: "Oman", code: "OMN" },
  { name: "Pakistan", code: "PAK" },
  { name: "Palau", code: "PLW" },
  { name: "Palestine", code: "PSE", alias: ["Palestine, State", "Palestinian Territories"] },
  { name: "Panama", code: "PAN" },
  { name: "Papua New Guinea", code: "PNG", alias: ["PNG"] },
  { name: "Paraguay", code: "PRY" },
  { name: "Peru", code: "PER" },
  { name: "Philippines", code: "PHL" },
  { name: "Pitcairn", code: "PCN" },
  { name: "Poland", code: "POL" },
  { name: "Portugal", code: "PRT" },
  { name: "Puerto Rico", code: "PRI" },
  { name: "Qatar", code: "QAT" },
  { name: "Romania", code: "ROU" },
  { name: "Russia", code: "RUS", alias: ["Russian Federation"] },
  { name: "Rwanda", code: "RWA" },
  { name: "Réunion", code: "REU", alias: ["Reunion"] },
  { name: "Saint Barthélemy", code: "BLM", alias: ["Saint Barthelemy"] },
  { name: "Saint Helena, Ascension and Tristan da Cunha", code: "SHN" },
  { name: "Saint Kitts and Nevis", code: "KNA", alias: ["St. Kitts and Nevis", "St Kitts and Nevis"] },
  { name: "Saint Lucia", code: "LCA", alias: ["St. Lucia", "St Lucia"] },
  { name: "Saint Martin (French part)", code: "MAF" },
  { name: "Saint Pierre and Miquelon", code: "SPM" },
  { name: "Saint Vincent and the Grenadines", code: "VCT", alias: ["St. Vincent and the Grenadines", "St Vincent and the Grenadines"] },
  { name: "Samoa", code: "WSM", alias: ["Western Samoa"] },
  { name: "San Marino", code: "SMR" },
  { name: "Sao Tome and Principe", code: "STP", alias: ["São Tomé and Príncipe"] },
  { name: "Saudi Arabia", code: "SAU", alias: ["KSA"] },
  { name: "Senegal", code: "SEN" },
  { name: "Serbia", code: "SRB" },
  { name: "Seychelles", code: "SYC" },
  { name: "Sierra Leone", code: "SLE" },
  { name: "Singapore", code: "SGP" },
  { name: "Sint Maarten (Dutch part)", code: "SXM" },
  { name: "Slovakia", code: "SVK", alias: ["Slovak Republic"] },
  { name: "Slovenia", code: "SVN" },
  { name: "Solomon Islands", code: "SLB" },
  { name: "Somalia", code: "SOM" },
  { name: "South Africa", code: "ZAF", alias: ["RSA"] },
  { name: "South Georgia and South Sandwich Islands", code: "SGS" },
  { name: "South Korea", code: "KOR", alias: ["Korea, Republic", "ROK"] },
  { name: "South Sudan", code: "SSD" },
  { name: "Spain", code: "ESP" },
  { name: "Sri Lanka", code: "LKA", alias: ["Ceylon"] },
  { name: "Sudan", code: "SDN" },
  { name: "Suriname", code: "SUR" },
  { name: "Svalbard and Jan Mayen", code: "SJM" },
  { name: "Sweden", code: "SWE" },
  { name: "Switzerland", code: "CHE" },
  { name: "Syria", code: "SYR", alias: ["Syrian Arab Republic"] },
  { name: "Taiwan", code: "TWN", alias: ["Republic of China", "Chinese Taipei"] },
  { name: "Tajikistan", code: "TJK" },
  { name: "Tanzania", code: "TZA", alias: ["Tanzania, United Republic"] },
  { name: "Thailand", code: "THA", alias: ["Siam"] },
  { name: "Timor-Leste", code: "TLS", alias: ["East Timor"] },
  { name: "Togo", code: "TGO" },
  { name: "Tokelau", code: "TKL" },
  { name: "Tonga", code: "TON" },
  { name: "Trinidad and Tobago", code: "TTO" },
  { name: "Tunisia", code: "TUN" },
  { name: "Turkey", code: "TUR", alias: ["Türkiye", "Turkiye"] },
  { name: "Turkmenistan", code: "TKM" },
  { name: "Turks and Caicos Islands", code: "TCA" },
  { name: "Tuvalu", code: "TUV" },
  { name: "Uganda", code: "UGA" },
  { name: "Ukraine", code: "UKR" },
  { name: "United Arab Emirates", code: "ARE", alias: ["UAE"] },
  { name: "United Kingdom", code: "GBR", alias: ["Great Britain", "UK"] },
  { name: "United States", code: "USA", alias: ["United States of America", "US", "USA"] },
  { name: "United States Minor Outlying Islands", code: "UMI" },
  { name: "Uruguay", code: "URY" },
  { name: "Uzbekistan", code: "UZB" },
  { name: "Vanuatu", code: "VUT", alias: ["New Hebrides"] },
  { name: "Venezuela", code: "VEN", alias: ["Venezuela, Bolivarian Republic"] },
  { name: "Vietnam", code: "VNM", alias: ["Viet Nam"] },
  { name: "Virgin Islands (British)", code: "VGB" },
  { name: "Virgin Islands (U.S.)", code: "VIR" },
  { name: "Wallis and Futuna", code: "WLF" },
  { name: "Western Sahara", code: "ESH" },
  { name: "Yemen", code: "YEM" },
  { name: "Zambia", code: "ZMB" },
  { name: "Zimbabwe", code: "ZWE" },
  { name: "Åland Islands", code: "ALA", alias: ["Aland Islands"] },
];

// Genuinely defunct states, not aliased to a modern country: their borders,
// government, or membership differ materially from any single present-day
// successor (a split, dissolution, or legally distinct former government),
// unlike the rename-only cases above (Zaire, Burma, Ceylon, Upper Volta,
// etc.) which are aliases since the same continuous state just renamed
// itself. Codes are the former ISO 3166-3 withdrawn codes, for historical
// MUN crisis committees (e.g. Cold War, Yugoslav Wars, decolonization).
export const historicalCountries = [
  { name: "Soviet Union", code: "SUN", alias: ["USSR", "CCCP", "Union of Soviet Socialist Republics"] },
  { name: "Yugoslavia", code: "YUG", alias: ["Socialist Federal Republic of Yugoslavia", "SFR Yugoslavia"] },
  { name: "Serbia and Montenegro", code: "SCG" },
  { name: "Czechoslovakia", code: "CSK" },
  { name: "East Germany", code: "DDR", alias: ["German Democratic Republic", "GDR"] },
  { name: "Rhodesia", code: "RHO", alias: ["Southern Rhodesia"] },
  { name: "North Vietnam", code: "VDR", alias: ["Democratic Republic of Vietnam"] },
  { name: "Netherlands Antilles", code: "ANT" },
  { name: "Pacific Islands, Trust Territory of the", code: "PCI" },
];


// Deliberately excludes generic words like "director"/"secretary"/"representative"/
// "officer": in real allocation sheets those also show up as delegate portfolio
// names (e.g. a crisis committee delegate called "BSAA Director" or "UNSC
// Representative"), so treating them as chair/page signals would misclassify data.
export const CHAIR_WORDS = new RegExp([
  "CHAIR",
  "PRESIDENT",
  "EDITOR",
  "DAIS",
  "MODERATOR",
  "PRESIDING",
  "RAPPORTEUR",
].join("|"));

export const PAGE_WORDS = new Set([
  "PAGE",
  "PAGES",
  "COURSIER",
  "COURSIERS",
  "MESSENGER",
  "MESSENGERS",
  "RUNNER",
  "RUNNERS",
  "USHER",
  "USHERS",
  // EISMUN embeds a per-committee support-staff photographer row
  // ("Photographer") alongside the delegate list - checked against every
  // country/role value across all 6 excelToJson sample files first, per
  // the rule below.
  "PHOTOGRAPHER",
  "PHOTOGRAPHERS",
]);

// Sheet names (exact, case-insensitive) that are never a real committee -
// cover/instructions/summary tabs some conferences include alongside the
// actual committee sheets.
export const SKIP_SHEETS = new Set([
  "teams",
  "information",
  "info",
  "cover",
  "cover page",
  "instructions",
  "read me",
  "readme",
  "summary",
  "notes",
  "overview",
  // EISMUN's whole-conference roster tab: advisors + secretariat +
  // parliamentarians, followed by a "Committees and Chairs" table that just
  // re-lists every chair already captured from their own committee sheet -
  // same role as "teams"/"information" above, just named differently.
  "chairs info",
]);

// Exact-match signals (post normalize()) that a row is a header row, and
// which field a header column maps to. Kept as sets (not a regex/substring
// check) because these are compared against a whole header cell, not
// scanned for as a substring of arbitrary data - "Delegate"/"Student" as a
// whole cell is a safe signal; as a substring of someone's real name it
// would not be.
export const NAME_WORDS = new Set([
  "NAME",
  "NOM",
  "NOMBRE",
  "DELEGATE",
  "STUDENT",
  "PARTICIPANT",
  "FULL NAME",
]);

export const EMAIL_WORDS = new Set([
  "EMAIL",
  "E-MAIL",
  "MAIL",
  "CORREO",
]);

export const TOPIC_WORDS = new Set([
  "TOPIC",
  "SUJET",
  "QUESTION",
  "THEME",
]);
